apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
  labels:
    type: mssql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/k8s/mssql-pv
    server: 192.168.159.20